AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for deploying Splunk AWS Logs Collector

Parameters:
  SplunkAPIKey:
    Type: String
  SplunkLogIngestUrl:
    Type: String
  SplunkMetricIngestUrl:
    Type: String
  IntegrationId:
    Type: String

Resources:
  SplunkAwsLogsCollector:
    Type: AWS::Serverless::Function
    Description: Splunk AWS Log Collector
    Properties:
      FunctionName: !Sub 'splunk-aws-logs-collector-${IntegrationId}'
      Runtime: python3.7
      Timeout: 60
      CodeUri: ./src
      Handler: function.lambda_handler
      Environment:
        Variables:
          SPLUNK_API_KEY: !Ref SplunkAPIKey
          SPLUNK_LOG_URL: !Ref SplunkLogIngestUrl
          SPLUNK_METRIC_URL: !Ref SplunkMetricIngestUrl
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
        - Statement:
            - Sid: AWSGetTagsOfResources
              Effect: Allow
              Action:
                - tag:GetResources
              Resource: "*"
        - Statement:
            - Sid: GetS3LogObjects
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: "*"
      Tags:
        splunk-log-collector-id: !Sub '${IntegrationId}:${AWS::Region}'

  SplunkAwsLogsCollectorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SplunkAwsLogsCollector
      Action: 'lambda:InvokeFunction'
      Principal: !Sub 'logs.${AWS::Region}.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'

  AllS3BucketsEventsCanInvokeLogCollector:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref SplunkAwsLogsCollector
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:s3:::*'

Outputs:
  LambdaArn:
    Value:
      Fn::GetAtt:
        - SplunkAwsLogsCollector
        - Arn
