AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Logs collector lambda

Resources:
  SplunkAwsLogsCollector:
    Type: AWS::Serverless::Function
    Description: Splunk AWS Log Collector
    Properties:
      FunctionName: 'splunk-aws-logs-collector'
      Runtime: python3.11
      Timeout: 60
      CodeUri: ./aws-log-collector.test.zip
      Handler: function.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole