AWSTemplateFormatVersion: '2010-09-09'
Description: Splunk Logs and Metric Streams Integration

Parameters:
  SplunkAPIKey:
    Type: String
    Description: Access Token
  SplunkLogIngestUrl:
    Type: String
    Description: Endpoint where AWS logs will be sent to
  SplunkMetricIngestUrl:
    Type: String
    Description: Endpoint where internal Splunk (used by Splunk to monitor lambda usage) will be sent to
  EnabledRegions:
    Type: CommaDelimitedList
    Description: Comma-delimited list of regions the functionality should be enabled in

Resources:
  SplunkAwsLogsCollectorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: splunk-log-collector
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Policies:
        - PolicyName: SplunkAwsLogsCollectorRolePolicyTag
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'tag:GetResources'
                Resource: '*'
                Sid: AWSGetTagsOfResources
        - PolicyName: SplunkAwsLogsCollectorRolePolicyS3
          PolicyDocument: 
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource: '*'
                Sid: GetS3LogObjects

  SplunkAwsLogsCollectorRegionalResources:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: SplunkAwsLogsCollectorRegionalResources
      Description: Create regional resources for Splunk AWS Logs Collector
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref EnabledRegions
      Parameters:
        - ParameterKey: SplunkAPIKey
          ParameterValue: !Ref SplunkAPIKey
        - ParameterKey: SplunkLogIngestUrl
          ParameterValue: !Ref SplunkLogIngestUrl
        - ParameterKey: SplunkMetricIngestUrl
          ParameterValue: !Ref SplunkMetricIngestUrl
        - ParameterKey: RoleArn
          ParameterValue: !GetAtt SplunkAwsLogsCollectorRole.Arn
      TemplateBody: |
          AWSTemplateFormatVersion: '2010-09-09'
          Description: Regional resources required by Splunk AWS Logs Collector
          Parameters:
            SplunkAPIKey:
              Type: String
            SplunkLogIngestUrl:
              Type: String
            SplunkMetricIngestUrl:
              Type: String
            RoleArn:
              Type: String
          Resources:
            SplunkAwsLogsCollector:
              Type: AWS::Lambda::Function
              Description: Splunk AWS Log Collector
              Properties:
                FunctionName: 'splunk-aws-logs-collector'
                Runtime: python3.7
                Timeout: 60
                Code: 
                  S3Bucket: !Sub 'o11y-public-${AWS::Region}'
                  S3Key: 'aws-log-collector/${LambdaCodeArchive}'
                Handler: function.lambda_handler
                Environment:
                  Variables:
                    SPLUNK_API_KEY: !Ref SplunkAPIKey
                    SPLUNK_LOG_URL: !Ref SplunkLogIngestUrl
                    SPLUNK_METRIC_URL: !Ref SplunkMetricIngestUrl
                Role: !Ref RoleArn
                Tags:
                  - Key: splunk-log-collector-id
                    Value: !Sub '${AWS::Region}'

            SplunkAwsLogsCollectorPermission:
              Type: AWS::Lambda::Permission
              Properties:
                FunctionName: !Ref SplunkAwsLogsCollector
                Action: 'lambda:InvokeFunction'
                Principal: !Sub 'logs.${AWS::Region}.amazonaws.com'
                SourceAccount: !Ref 'AWS::AccountId'
                SourceArn: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'

            AllS3BucketsEventsCanInvokeLogCollector:
              Type: AWS::Lambda::Permission
              Properties:
                Action: 'lambda:InvokeFunction'
                FunctionName: !Ref SplunkAwsLogsCollector
                Principal: s3.amazonaws.com
                SourceAccount: !Ref 'AWS::AccountId'
                SourceArn: !Sub 'arn:aws:s3:::*'
