AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for deploying Splunk AWS Logs Forwarder

Parameters:
  SplunkAPIKey:
    Type: String
  SplunkLogIngestUrl:
    Type: String

Resources:
  SplunkAwsLogsForwarder:
    Type: AWS::Serverless::Function
    Description: WIP SplunkAwsLogsForwarder
    Properties:
      FunctionName: splunk-aws-logs-forwarder
      Runtime: python3.7
      Timeout: 60
      CodeUri: ./src
      Handler: function.lambda_handler
      Environment:
        Variables:
          SPLUNK_API_KEY: !Ref SplunkAPIKey
          SPLUNK_URL: !Ref SplunkLogIngestUrl
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: AWSGetTagsOfResources
              Effect: Allow
              Action:
                - tag:GetResources
              Resource: '*'

Outputs:
  LambdaArn:
    Value:
      Fn::GetAtt:
        - SplunkAwsLogsForwarder
        - Arn