AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for deploying Splunk AWS Logs Collector

Parameters:
  SplunkAPIKey:
    Type: String
  SplunkLogIngestUrl:
    Type: String
  IntegrationId:
    Type: String

Resources:
  SplunkAwsLogsCollector:
    Type: AWS::Serverless::Function
    Description: Splunk AWS Log Collector
    Properties:
      FunctionName: !Join [ '-', ['splunk-aws-logs-collector', !Ref IntegrationId] ]
      Runtime: python3.7
      Timeout: 60
      CodeUri: ./src
      Handler: function.lambda_handler
      Environment:
        Variables:
          SPLUNK_API_KEY: !Ref SplunkAPIKey
          SPLUNK_URL: !Ref SplunkLogIngestUrl
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: AWSGetTagsOfResources
              Effect: Allow
              Action:
                - tag:GetResources
              Resource: '*'
      Tags:
        SplunkId: !Join [ '-', [ 'aws-log-collector', !Ref IntegrationId, !Ref 'AWS::Region' ] ]

Outputs:
  LambdaArn:
    Value:
      Fn::GetAtt:
        - SplunkAwsLogsCollector
        - Arn