version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:

  build-and-test:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make init
          name: Install dependencies
      - run:
# test_e2e.py is included
          command: |
            . venv/bin/activate
            make test AWS_DEFAULT_REGION=eu-central-1
          name: Run unit test
      - run:
# || true makes the step pass even if the linter returns an error, which is currently the case
          command: |
            . venv/bin/activate
            make lint || true
          name: Run lint. This step may be failing for now.

  zip-and-save-test:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          command: make local-zip
          name: Create stage zip locally
      - persist_to_workspace:
          root: .
          paths:
            - aws-log-collector.test.zip

  zip-and-save-stage:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          command: make stage-zip
          name: Create stage zip locally
      - persist_to_workspace:
          root: .
          paths:
            - aws-log-collector.stage.zip

  zip-and-save-release:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          command: make release-zip
          name: Create release zip locally
      - persist_to_workspace:
          root: .
          paths:
            - aws-log-collector.release.zip

  upload-test:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: make publish-release ZIP=aws-log-collector.test.zip
          name: Publish test zip to rnd account.

  upload-stage:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: make publish-release ZIP=aws-log-collector.stage.zip
          name: Publish stage zip to rnd account.

  upload-release:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - checkout
      - attach_workspace:
          at: .
      #REGIONS can be passed in ENV variable to run the job only in selected regions
      #PUBLIC means public-read acl will be added to artifacts
      - run:
          command: make publish-release PUBLIC=true ZIP=aws-log-collector.release.zip
          name: Publish release zip to rnd account.

workflows:
  main:
    jobs:
      - build-and-test
      - zip-and-save-test:
          requires:
            - build-and-test
      - upload-test:
          requires:
            - zip-and-save-test
      - zip-and-save-stage:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
            tags:
              ignore: /^\d+\.\d+\.\d+$/
      - upload-stage:
          requires:
            - zip-and-save-stage
          filters:
            branches:
              only: main
            tags:
              ignore: /^\d+\.\d+\.\d+$/
      - zip-and-save-release:
          requires:
            - build-and-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - upload-release:
          requires:
            - zip-and-save-release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
